# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connect-4.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63onnect-4.proto\x12\tconnect_4\")\n\x0bJoinRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x63olour\x18\x02 \x01(\x05\"@\n\x0cJoinResponse\x12\x0e\n\x06roomid\x18\x01 \x01(\t\x12\x10\n\x08\x63lientid\x18\x02 \x01(\t\x12\x0e\n\x06\x63olour\x18\x03 \x01(\x05\"\x1d\n\x0bMoveRequest\x12\x0e\n\x06\x63olumn\x18\x01 \x01(\x05\"\x1e\n\x0cMoveResponse\x12\x0e\n\x06\x63olumn\x18\x01 \x01(\x05\"\x19\n\x0bInitRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xc9\x01\n\tConnect_4\x12?\n\x08JoinRoom\x12\x16.connect_4.JoinRequest\x1a\x17.connect_4.JoinResponse\"\x00\x30\x01\x12\x39\n\x04Move\x12\x16.connect_4.MoveRequest\x1a\x17.connect_4.MoveResponse\"\x00\x12@\n\x0b\x46irstMoveP2\x12\x16.connect_4.InitRequest\x1a\x17.connect_4.MoveResponse\"\x00\x42\x36\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connect_4_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG'
  _JOINREQUEST._serialized_start=30
  _JOINREQUEST._serialized_end=71
  _JOINRESPONSE._serialized_start=73
  _JOINRESPONSE._serialized_end=137
  _MOVEREQUEST._serialized_start=139
  _MOVEREQUEST._serialized_end=168
  _MOVERESPONSE._serialized_start=170
  _MOVERESPONSE._serialized_end=200
  _INITREQUEST._serialized_start=202
  _INITREQUEST._serialized_end=227
  _CONNECT_4._serialized_start=230
  _CONNECT_4._serialized_end=431
# @@protoc_insertion_point(module_scope)
