# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import connect_4_pb2 as flaskr_dot_protos_dot_connect__4__pb2


class Connect_4Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinRoom = channel.unary_stream(
                '/connect_4.Connect_4/JoinRoom',
                request_serializer=flaskr_dot_protos_dot_connect__4__pb2.JoinRequest.SerializeToString,
                response_deserializer=flaskr_dot_protos_dot_connect__4__pb2.JoinResponse.FromString,
                )
        self.Move = channel.unary_unary(
                '/connect_4.Connect_4/Move',
                request_serializer=flaskr_dot_protos_dot_connect__4__pb2.MoveRequest.SerializeToString,
                response_deserializer=flaskr_dot_protos_dot_connect__4__pb2.MoveResponse.FromString,
                )
        self.FirstMoveP2 = channel.unary_unary(
                '/connect_4.Connect_4/FirstMoveP2',
                request_serializer=flaskr_dot_protos_dot_connect__4__pb2.InitRequest.SerializeToString,
                response_deserializer=flaskr_dot_protos_dot_connect__4__pb2.MoveResponse.FromString,
                )
        self.End = channel.unary_unary(
                '/connect_4.Connect_4/End',
                request_serializer=flaskr_dot_protos_dot_connect__4__pb2.MoveRequest.SerializeToString,
                response_deserializer=flaskr_dot_protos_dot_connect__4__pb2.EndRequest.FromString,
                )


class Connect_4Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FirstMoveP2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def End(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Connect_4Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinRoom': grpc.unary_stream_rpc_method_handler(
                    servicer.JoinRoom,
                    request_deserializer=flaskr_dot_protos_dot_connect__4__pb2.JoinRequest.FromString,
                    response_serializer=flaskr_dot_protos_dot_connect__4__pb2.JoinResponse.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=flaskr_dot_protos_dot_connect__4__pb2.MoveRequest.FromString,
                    response_serializer=flaskr_dot_protos_dot_connect__4__pb2.MoveResponse.SerializeToString,
            ),
            'FirstMoveP2': grpc.unary_unary_rpc_method_handler(
                    servicer.FirstMoveP2,
                    request_deserializer=flaskr_dot_protos_dot_connect__4__pb2.InitRequest.FromString,
                    response_serializer=flaskr_dot_protos_dot_connect__4__pb2.MoveResponse.SerializeToString,
            ),
            'End': grpc.unary_unary_rpc_method_handler(
                    servicer.End,
                    request_deserializer=flaskr_dot_protos_dot_connect__4__pb2.MoveRequest.FromString,
                    response_serializer=flaskr_dot_protos_dot_connect__4__pb2.EndRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'connect_4.Connect_4', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Connect_4(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/connect_4.Connect_4/JoinRoom',
            flaskr_dot_protos_dot_connect__4__pb2.JoinRequest.SerializeToString,
            flaskr_dot_protos_dot_connect__4__pb2.JoinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/connect_4.Connect_4/Move',
            flaskr_dot_protos_dot_connect__4__pb2.MoveRequest.SerializeToString,
            flaskr_dot_protos_dot_connect__4__pb2.MoveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FirstMoveP2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/connect_4.Connect_4/FirstMoveP2',
            flaskr_dot_protos_dot_connect__4__pb2.InitRequest.SerializeToString,
            flaskr_dot_protos_dot_connect__4__pb2.MoveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def End(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/connect_4.Connect_4/End',
            flaskr_dot_protos_dot_connect__4__pb2.MoveRequest.SerializeToString,
            flaskr_dot_protos_dot_connect__4__pb2.EndRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
